sudo: required

language: nix

services:
- docker

cache:
  directories:
  - $HOME/nix.store

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

before_cache:
- mkdir -p $HOME/nix.store
- nix copy --to file://$HOME/nix.store -f default.nix buildInputs

before_script:
- sudo mkdir -p /etc/nix && echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

script:
##-- version check --
- docker --version
- nix --version
##-- building --
- nix-env -if https://github.com/cachix/cachix/tarball/master --extra-substituters https://cachix.cachix.org --trusted-public-keys 'cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM='
- cachix use wizzup
- cachix push wizzup --watch-store 2>&1 1>cachix.log &
- nix-build -j2 | cachix push wizzup
##-- loading --
- docker load < result
- docker ps -a
- docker images -a
##-- testing --
- docker run --rm hs-stack
